2023-04-23 22:27:05,348 ERROR: Exception on /index [GET] [in C:\xampp\htdocs\@my\@python\microblog\venv\lib\site-packages\flask\app.py:1744]
Traceback (most recent call last):
  File "C:\xampp\htdocs\@my\@python\microblog\venv\lib\site-packages\flask\app.py", line 2528, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\xampp\htdocs\@my\@python\microblog\venv\lib\site-packages\flask\app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\xampp\htdocs\@my\@python\microblog\venv\lib\site-packages\flask\app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\xampp\htdocs\@my\@python\microblog\venv\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "C:\xampp\htdocs\@my\@python\microblog\venv\lib\site-packages\flask_login\utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "C:\xampp\htdocs\@my\@python\microblog\app\routes.py", line 42, in index
    return render_template('index.html', title=_('Home'), form=form, posts=posts.items, next_url=next_url, prev_url=prev_url)
  File "C:\xampp\htdocs\@my\@python\microblog\venv\lib\site-packages\flask\templating.py", line 147, in render_template
    return _render(app, template, context)
  File "C:\xampp\htdocs\@my\@python\microblog\venv\lib\site-packages\flask\templating.py", line 130, in _render
    rv = template.render(context)
  File "C:\xampp\htdocs\@my\@python\microblog\venv\lib\site-packages\jinja2\environment.py", line 1301, in render
    self.environment.handle_exception()
  File "C:\xampp\htdocs\@my\@python\microblog\venv\lib\site-packages\jinja2\environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "C:\xampp\htdocs\@my\@python\microblog\app\templates\index.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "C:\xampp\htdocs\@my\@python\microblog\venv\lib\site-packages\jinja2\environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "C:\xampp\htdocs\@my\@python\microblog\app\templates\base.html", line 84, in template
    $(destElem).html('<img src="{{ url_for(\'static\', filename=\'loading.gif\') }}">');
jinja2.exceptions.TemplateSyntaxError: unexpected char '\\' at 4327
2023-04-23 22:44:47,323 INFO: Microblog startup [in C:\xampp\htdocs\@my\@python\microblog\app\__init__.py:53]
2023-04-23 22:44:51,989 ERROR: Exception on /index [GET] [in C:\xampp\htdocs\@my\@python\microblog\venv\lib\site-packages\flask\app.py:1744]
Traceback (most recent call last):
  File "C:\xampp\htdocs\@my\@python\microblog\venv\lib\site-packages\flask\app.py", line 2528, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\xampp\htdocs\@my\@python\microblog\venv\lib\site-packages\flask\app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\xampp\htdocs\@my\@python\microblog\venv\lib\site-packages\flask\app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\xampp\htdocs\@my\@python\microblog\venv\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "C:\xampp\htdocs\@my\@python\microblog\venv\lib\site-packages\flask_login\utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "C:\xampp\htdocs\@my\@python\microblog\app\routes.py", line 42, in index
    return render_template('index.html', title=_('Home'), form=form, posts=posts.items, next_url=next_url, prev_url=prev_url)
  File "C:\xampp\htdocs\@my\@python\microblog\venv\lib\site-packages\flask\templating.py", line 147, in render_template
    return _render(app, template, context)
  File "C:\xampp\htdocs\@my\@python\microblog\venv\lib\site-packages\flask\templating.py", line 130, in _render
    rv = template.render(context)
  File "C:\xampp\htdocs\@my\@python\microblog\venv\lib\site-packages\jinja2\environment.py", line 1301, in render
    self.environment.handle_exception()
  File "C:\xampp\htdocs\@my\@python\microblog\venv\lib\site-packages\jinja2\environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "C:\xampp\htdocs\@my\@python\microblog\app\templates\index.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "C:\xampp\htdocs\@my\@python\microblog\venv\lib\site-packages\jinja2\environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "C:\xampp\htdocs\@my\@python\microblog\app\templates\base.html", line 83, in template
    document.getElementById('destElem').innerHTML = '<img src="{{ url_for(\'static\', filename=\'loading.gif\') }}">';
jinja2.exceptions.TemplateSyntaxError: unexpected char '\\' at 4321
2023-04-23 22:45:19,018 ERROR: Exception on /index [GET] [in C:\xampp\htdocs\@my\@python\microblog\venv\lib\site-packages\flask\app.py:1744]
Traceback (most recent call last):
  File "C:\xampp\htdocs\@my\@python\microblog\venv\lib\site-packages\flask\app.py", line 2528, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\xampp\htdocs\@my\@python\microblog\venv\lib\site-packages\flask\app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\xampp\htdocs\@my\@python\microblog\venv\lib\site-packages\flask\app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\xampp\htdocs\@my\@python\microblog\venv\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "C:\xampp\htdocs\@my\@python\microblog\venv\lib\site-packages\flask_login\utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "C:\xampp\htdocs\@my\@python\microblog\app\routes.py", line 42, in index
    return render_template('index.html', title=_('Home'), form=form, posts=posts.items, next_url=next_url, prev_url=prev_url)
  File "C:\xampp\htdocs\@my\@python\microblog\venv\lib\site-packages\flask\templating.py", line 147, in render_template
    return _render(app, template, context)
  File "C:\xampp\htdocs\@my\@python\microblog\venv\lib\site-packages\flask\templating.py", line 130, in _render
    rv = template.render(context)
  File "C:\xampp\htdocs\@my\@python\microblog\venv\lib\site-packages\jinja2\environment.py", line 1301, in render
    self.environment.handle_exception()
  File "C:\xampp\htdocs\@my\@python\microblog\venv\lib\site-packages\jinja2\environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "C:\xampp\htdocs\@my\@python\microblog\app\templates\index.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "C:\xampp\htdocs\@my\@python\microblog\venv\lib\site-packages\jinja2\environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "C:\xampp\htdocs\@my\@python\microblog\app\templates\base.html", line 83, in template
    document.getElementById('destElem').innerHTML = '<img src="{{ url_for(\"static\", filename=\"loading.gif\") }}">';
jinja2.exceptions.TemplateSyntaxError: unexpected char '\\' at 4321
2023-04-23 22:56:59,717 INFO: Microblog startup [in C:\xampp\htdocs\@my\@python\microblog\app\__init__.py:53]
2023-04-23 23:02:28,705 INFO: Microblog startup [in C:\xampp\htdocs\@my\@python\microblog\app\__init__.py:53]
2023-05-02 17:30:40,550 INFO: Microblog startup [in C:\xampp\htdocs\@my\@python\microblog\app\__init__.py:53]
2023-05-02 17:34:12,519 INFO: Microblog startup [in C:\xampp\htdocs\@my\@python\microblog\app\__init__.py:53]
2023-05-02 17:34:28,728 INFO: Microblog startup [in C:\xampp\htdocs\@my\@python\microblog\app\__init__.py:53]
2023-05-02 18:35:11,845 INFO: Microblog startup [in C:\xampp\htdocs\@my\@python\microblog\app\__init__.py:73]
2023-05-02 19:02:31,491 INFO: Microblog startup [in C:\xampp\htdocs\@my\@python\microblog\app\__init__.py:77]
2023-05-02 19:05:54,783 INFO: Microblog startup [in C:\xampp\htdocs\@my\@python\microblog\app\__init__.py:77]
2023-05-02 19:11:40,027 INFO: Microblog startup [in C:\xampp\htdocs\@my\@python\microblog\app\__init__.py:77]
2023-05-02 19:11:54,229 INFO: Microblog startup [in C:\xampp\htdocs\@my\@python\microblog\app\__init__.py:77]
2023-05-02 19:24:38,804 INFO: Microblog startup [in C:\xampp\htdocs\@my\@python\microblog\app\__init__.py:77]
2023-05-03 11:33:39,937 INFO: Microblog startup [in C:\xampp\htdocs\@my\@python\microblog\app\__init__.py:77]
